// `npm run compile`

import './doc.js' // Also document.

// Minify.
import {rollup} from 'rollup'
import {minify} from 'terser'
const code = (await minify(
    (await (await rollup({
        input: './main.js',
    })).generate({})).output[0].code,
    {
        keep_classnames: true,
    },
)).code

// Save.
import fs from 'fs'
fs.writeFileSync('./main.min.js', code)
console.log('OK  ', 'Minified', code.length+'B', 'into sn/js-lib/main.min.js')

// Set up the `/docs` to contain our test page.
//   (A simple copy, which, as a bonus, inflates our commit line-count unfairly.)
const h = "// (Auto-generated by `npm run compile`.)\n"
fs.writeFileSync('../docs/index.html', fs.readFileSync('./test/test.html', 'utf8').replace("import sn from '../main.js'", "import sn from './main.min.js'"))
fs.writeFileSync('../docs/plots.js', h+fs.readFileSync('./test/plots.js'))
fs.writeFileSync('../docs/smooth-collapse.js', h+fs.readFileSync('./test/smooth-collapse.js'))
fs.writeFileSync('../docs/main.min.js', code)

console.log('OK  ', 'Set up /docs')